# -*- coding: utf-8 -*-
"""Workshop1_AI_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wJrrFz2GBH19VnsX24PUlPBzn9FQbfZN
"""

pip install pillow

from PIL import Image
#display image in colab
image_colored = Image.open("/content/drive/MyDrive/AI_ML/Data/eye.png")
display (image_colored)

print("Image Format:", image_colored.format)
print("Image Size:", image_colored.size)
print("Image Mode:", image_colored.mode)

# Get the size (width , height ) and channels (RGB)
width , height = image_colored . size
channels = len( image_colored . getbands () ) # For RGB , it will be
print ( f" Image shape (RGB): ({ height } , { width } , { channels})")
image_size_colored = width * height *3
print ( f" Image size (RGB): { image_size_colored }")

import numpy as np
import matplotlib.pyplot as plt
# Convert the Pillow image to a NumPy array
image_array_colored = np . array ( image_colored )
# Display the shape of the NumPy array (height , width ,channels )
print (" Shape of the image array :", image_array_colored . shape)
#For Red Channels
red_channel = image_array_colored [: , : , 0] # Red channel
print ( red_channel )
display ( red_channel )
plt.imshow ( red_channel)
# For Green Channels
green_channel = image_array_colored [: , : , 1] # Greenchannel
print ( green_channel )
display ( green_channel )
plt.imshow ( green_channel)
# For Blue Channel :
blue_channel = image_array_colored [: , : , 2] # Blue channel
print ( blue_channel )
display ( blue_channel )
plt.imshow ( blue_channel)

import numpy as np
import matplotlib.pyplot as plt
# Assuming image_colored is already defined and loaded above
# Get the R, G, B, and A channels
r , g , b , a = image_colored . split ()
 # Display or further process the individual channels
display ( r )
display ( g )
display ( b )
display ( a ) # Display the alpha channel as well

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
# Load image and convert to grayscale
# Make sure 'image_cameraman.jpg' is uploaded to your Colab environment or provide the correct path.
image = Image.open("/content/drive/MyDrive/AI_ML/Data/eye.png").convert("L")
# Convert to NumPy array
image_array = np.array(image)
# Get image dimensions
height, width = image_array.shape
# Reshape the image into a 2D array where each row represents a row of pixels
# This allows PCA to process each row as an observation and find patterns across pixel intensities
data = image_array.reshape(height, width)

from sklearn.decomposition import PCA

# Center the data (important for PCA)
mean_data = data.mean(axis=0)
centered_data = data - mean_data

# Create a PCA model
pca = PCA()

# Fit PCA to the data
pca.fit(centered_data)

# Get the eigenvalues (explained variance)
eigenvalues = pca.explained_variance_

# Plot the explained variance ratio
explained_variance_ratio = eigenvalues / np.sum(eigenvalues)
plt.plot(np.cumsum(explained_variance_ratio))
plt.title("Cumulative Explained Variance")
plt.xlabel("Number of Components")
plt.ylabel("Cumulative Explained Variance")
plt.grid(True)
plt.show()

k = 50  # Number of components for compression, choose based on explained variance plot

# Apply PCA to transform the centered data to the full principal component space.
# The 'pca' object learned min(height, width) = min(836, 1258) = 836 components.
transformed_data_all_components = pca.transform(centered_data)

# Select only the top 'k' components for the compressed representation.
compressed_data = transformed_data_all_components[:, :k]

# To perform inverse_transform correctly, we need to create an array
# that matches the full dimensionality of the PCA model's component space (836 components)
# and place our 'k' compressed components into it, filling the rest with zeros.
compressed_data_for_inverse_transform = np.zeros_like(transformed_data_all_components)
compressed_data_for_inverse_transform[:, :k] = compressed_data

# Inverse transform to get the decompressed image (approximately)
decompressed_data = pca.inverse_transform(compressed_data_for_inverse_transform)

# Add back the mean to get the original scale
decompressed_data = decompressed_data + mean_data

# Reshape the decompressed data back to the original image dimensions
decompressed_data = decompressed_data.reshape(height, width)

plt . figure ( figsize =(12 , 6) )
# Original Image
plt . subplot (1 , 3 , 1)
plt . imshow ( image_array , cmap ="gray")
plt . title ("Original Image")
plt . axis ("off")
# Compressed Representation
# Note: compressed_data is typically a 2D array (samples x components),
# so directly plotting it might not yield a visually interpretable image
# in the same way as decompressed_data. We'll plot it as is to show its structure.
plt . subplot (1 , 3 , 2)
plt . imshow ( compressed_data , cmap ="gray", aspect ="auto")
plt . title ( f"Compressed Representation (k={k})")
plt . axis ("off")
# Decompressed Image
plt . subplot (1 , 3 , 3)
plt . imshow ( decompressed_data , cmap ="gray")
plt . title ("Decompressed Image")
plt . axis ("off")
plt . tight_layout ()
plt . show ()